baseurl = "/"
languageCode = "en-us"
title = "AUVIC"

[params]
  description = "AUVIC club site. For info about team and competitions"

[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 1

[[menu.main]]
    name = "Contact"
    url  = "/contact"
    weight = 1

[[menu.main]]
    name = "Events"
    url  = "/events"
    weight = 1

[[menu.main]]
    name = "Media"
    url  = "/media"
    weight = 1

[[menu.main]]
    name = "Meeting-Times"
    url  = "/meeting-times"
    weight = 1

[[menu.main]]
    name = "Sponsors"
    url  = "/Sponsors"
    weight = 1

[[menu.main]]
    name = "Sponsors"
    url  = "/Sponsors"
    weight = 1

[[menu.main]]
    name = "Team"
    url  = "/team"
    weight = 1
  
